apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  annotations:
    kubernetes.io/change-reason: "Start config"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: fc-kubernetes/express-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
