apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  annotations:
    kubernetes.io/change-reason: "Start config"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: fc-kubernetes/express-app:v3.2
        imagePullPolicy: IfNotPresent
        # env:
        #   - name: USER_NAME
        #     value: "Ítalo"
        #   - name: USER_AGE
        #     value: "28"

        # env:
        #   - name: USER_NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: express-env
        #         key: USER_NAME
            
        #   - name: USER_AGE
        #     valueFrom:
        #       configMapKeyRef:
        #         name: express-env
        #         key: USER_AGE

        envFrom:
          - configMapRef:
              name: express-env

          - secretRef:
              name: app-secrets

        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        # mounts the referenced config map volume into the container
        volumeMounts:
          - mountPath: "/app/myfamily"
            name: app-config-volume

      # creates a volume shared between the containers using a config map and converts it into a file in /app/myfamily
      volumes:
        - name: app-config-volume
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
